// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "onevote/models"

type ChainData struct {
	Blocks []models.Block
}

func ChainTempl(data ChainData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"es\"><head><link rel=\"stylesheet\" href=\"/static/chain.css\"><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Vote Submission</title><script src=\"https://unpkg.com/htmx.org@2.0.3\"></script></head><body><h2>Blockchain</h2><!-- Container where the blockchain data will be loaded --><div id=\"chain\" hx-get=\"/chain\" hx-trigger=\"load, every 1s\" hx-swap=\"innerHTML\"></div><!-- Template for displaying blockchain data in Go --><script type=\"text/htmx-template\" id=\"block-template\">\r\n\t\t\t\t{{ range .Blocks }}\r\n\t\t\t\t\t<div class=\"block\">\r\n\t\t\t\t\t\t<h3>Block Number: {{ .BlockNumber }}</h3>\r\n\t\t\t\t\t\t<p><strong>Previous Hash:</strong> {{ .PreviousHash }}</p>\r\n\t\t\t\t\t\t<p><strong>Timestamp:</strong> {{ .Timestamp }}</p>\r\n\t\t\t\t\t\t<p><strong>Votes:</strong></p>\r\n\t\t\t\t\t\t<ul>\r\n\t\t\t\t\t\t\t{{ range .Votes }}\r\n\t\t\t\t\t\t\t\t<li>{{ .VoterID }} voted for {{ .CandidatoID }} at {{ .SedeID }} ({{ .TipoVoto }})</li>\r\n\t\t\t\t\t\t\t{{ end }}\r\n\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t<p><strong>Current Hash:</strong> {{ .CurrentHash }}</p>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t{{ end }}\r\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
